---
- name: Install Homebrew packages
  hosts: localhost
  gather_facts: false
  become: false

  vars:
    brew_tap_packages: []
    brew_packages:
      - "zsh"

  tasks:
    - name: Installing Homebrew Cask Packages
      homebrew_tap:
        name: "{{ item }}"
        state: present
      with_items: "{{ brew_tap_packages }}"
      register: result
      until: result is successful

    - name: Installing Homebrew Packages
      homebrew:
        name: "{{ item }}"
        state: present
      with_items: "{{ brew_packages }}"
      register: result
      until: result is successful
