---
- name: Install Homebrew packages
  hosts: localhost
  gather_facts: false
  become: false

  vars:
    brew_tap_packages:
      - "siderolabs/tap"
      - "fluxcd/tap"
      - "int128/kubelogin"
    brew_packages:
      - "talosctl"
      - "kubectl"
      - "flux"
      - "argo"
      - "kubelogin"
      - "helm"

  pre_tasks:
    - name: Check if Homebrew is installed
      command: brew --version
      register: homebrew_check
      ignore_errors: true

    - name: Install Homebrew if not found
      command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when: homebrew_check.failed

    - name: Update Homebrew
      homebrew:
        update_homebrew: true
      when: not homebrew_check.failed


  tasks:
    - name: Installing Homebrew Cask Packages
      homebrew_tap:
        name: "{{ item }}"
        state: present
      with_items: "{{ brew_tap_packages }}"
      register: result
      until: result is successful

    - name: Installing Homebrew Packages
      homebrew:
        name: "{{ item }}"
        state: present
      with_items: "{{ brew_packages }}"
      register: result
      until: result is successful
